### ISSUE TITLE
Concrete exceptions should have abstract parent to allow try-catch, etc to work properly.

### ISSUE THREAD

**Issue by MrTrick** [crazycodr/standard-exceptions#1]
Your tree makes sense, from an organisation and use point of view.  
However, I'd expect to be able to use this kind of pattern;

```
try {  MyModel::save($data); } 
catch (ValidationException $e) { ...do the appropriate thing about bad input... }
catch (IOException $e) { ...do the appropriate thing about a bad connection/file/backend... }
```

I suggest an abstract parent class for each group of exceptions.

**Comment by crazycodr** [comment]
Agreed, for some use cases, it would be logical to have them. Right now, the only one that does have that is the ValidationException group with InvalidValueException because none (or almost none of them) actually extend anything from the official SPL tree.

If i do not want to be SPL compatible, then there are TONS of things i'd change to this package to make it more usable... I've had a bunch of recent stars to it and i see people are starting to use it. Maybe it is time to go to version 2 which will not be SPL backward compatible but offer a real stronger structure!

**Comment by crazycodr** [comment]
https://github.com/crazycodr/standard-exceptions/tree/version2

**Comment by crazycodr** [comment]
@MrTrick Check version 2, there are now base exceptions, interfaces and even better, a nifty trick i had thought about some time ago that i call Tag interfaces which allow means to be abstracted away and caught instead of relying on context based exceptions!

**Comment by MrTrick** [comment]
@crazycodr Looks good, but something seems wrong about defining `getHttpCode()` in every child class when it's really a shared feature of every HTTP exception.

**Comment by crazycodr** [comment]
There is, but it is called base exception... you suggest i rename it to the namespace name?

**Comment by crazycodr** [comment]
And there is an exception in case you already have an exception tree and just want to tag it in

**Comment by crazycodr** [comment]
@MrTrick I'll see to it too, tell me what you think about the base exception and then i,ll do both!

**Comment by MrTrick** [comment]
@crazycodr I think 'HttpException' makes sense as a base name, yes.

I've thought about the role of exceptions a bit more, and I'm not sure any more that the HTTP namespace makes sense.  
Consider that an exception's class indicates its source. The thrown exceptions `Zend_Ldap_Exception`, `ParseException`, `PDOException`, and `\StandardExceptions\Validation\InvalidFormatException` all indicate their source; a problem communicating with LDAP, a problem parsing something, a problem accessing the database, and a problem trying to validate the format of something.  By the same logic, an `HTTP` exception should probably mean "A problem happened when PHP tried to access something over HTTP".
(Which does happen, and does exist, eg `Zend_Http_Client_Adapter_Exception`

There's plenty of stuff out there about how to craft HTTP responses. There's even a PSR: http://www.php-fig.org/psr/psr-7/  
I guess the missing component is a best-practice way to transform source exceptions into the right kind of response. An `InvalidFormatException` might merit a 401, a 403, a 404, or even a 50x error response, depending where it occurs.

**Comment by crazycodr** [comment]
Interesting point of view... I wanted to recreate these exceptions to make sure that other frameworks stop recreating them. Many frameworks use HTTP exceptions to return the correct exception message or intercept the page response and do something before it such as showing a 404 page instead of showing a raw 404 page from the server.

So i don't think these will be moved away but i will definitely check psr-7 to make sure!

**Comment by MrTrick** [comment]
Sorry if I came across as overly blunt. Yes that's quite true, many frameworks use HTTP exceptions as a mechanism to trigger the appropriate kind of error response. 

An HTTPException might be built when a component catches a more-specific exception, and then re-thrown. According to the principle of least knowledge, it should be done by a component that **knows** it is part of a web server and what kind of HTTP error is appropriate in that context. (as opposed to a low-level storage component, or top-level index.php) At a minimum, it should have visibility of the Response object...

**Comment by crazycodr** [comment]
Agreed about throwing and catching exceptions based on HTTP... A component should return something specific... Have you looked at the documentation around the exception tagging... this is like THE hot thing about the package...

**Comment by crazycodr** [comment]
Fixed by https://github.com/crazycodr/standard-exceptions/releases/tag/2.0.0

**Comment by robertmain** [comment]
Adding to this - is there any chance that it will implement `Throwable`? So that I can type-hint that into my exception handler?

**Comment by crazycodr** [comment]
I'll look into this, i haven't seen this update to PHP but i'm sure it would be welcome... If you know more about this, just create a PR with the throwable interface, i'll try to do it in a reasonable amount of time if not!

**Comment by crazycodr** [comment]
I just took a really quick look at it and this is what i found:

> Note:
> PHP classes cannot implement the Throwable interface directly, and must instead extend Exception.

If all my exceptions extend \Exception, then they are all throwable... no?

**Comment by robertmain** [comment]
Ah, yeah. You're right. Missed that somehow...

Either way, it would be neat if you had a base exception that I could catch :)

**Comment by crazycodr** [comment]
There is no reason to add a base exception to catch only exceptions from my package as my package is not a set of related exceptions but a set of various reusable exceptions. If you want to catch any exception from my package, you have a problem at your architectural level because you should never need to catch ANY exception and if you want to catch any exception, then just catch \Exception.

**Comment by robertmain** [comment]
Yeah, maybe I should be looking to catch the base HTTP exception.
