### ISSUE TITLE
Feature Request: Factory (kind of) for Http exceptions

### ISSUE THREAD

**Issue by Gounlaf** [crazycodr/standard-exceptions#18]
Hi,

I'm encountering a recurrent usage of the Http exceptions: always need to check some "http response code" and instantiate the appropriate exception available in namespace `Exceptions\Http`.

Do you mind to have kind of Factory like this:

`buildException(int $responseCode, string $message = "", \Throwable $previous = null)`

Or maybe, coupled with #17, it can attach the response as a "context".

`buildException(\Psr\Http\Message\ResponseInterface $response, string $message = "", \Throwable $previous = null)`

The 2nd option add more dependency... So I might be "too much"; at least the 1st option should be great.

I'm able to do a PR if you want/need (and are OK with this idea)

Thanks,

Regards.

**Comment by crazycodr** [comment]
I don't think it makes sense to make an exception based on a PSR7 response. The reverse would make sense. Some kind of exception handler that transforms the HttpExceptions into PSR7 responses makes more sense because you should not send an exception back to a client.

That being said, i'm sure you can find a reason to do this, like in a pipeline processing as a a request proxy handler but in a normal scenario, i think this would be a anti-pattern or a reversed pattern usage.

Let's chat this out a little more before accepting such a solution just to make sure.

**Comment by Gounlaf** [comment]
> I don't think it makes sense to make an exception based on a PSR7 response. The reverse would make sense. Some kind of exception handler that transforms the HttpExceptions into PSR7 responses makes more sense because you should not send an exception back to a client.

I totaly agree.
